name: Compute Benchmarks Nightly

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  push:

permissions:
  contents: read
  pull-requests: write

jobs:
  nightly:
    if: github.event_name == 'schedule'
    name: Nightly Compute Benchmarks
    uses: ./.github/workflows/benchmarks-reusable.yml
    with:
      str_name: 'level_zero'
      unit: 'gpu'
      pr_no: 0
      bench_script_params: '--save baseline'
      sycl_config_params: ''
      sycl_repo: 'intel/llvm'
      sycl_commit: ''

  push:
    if: github.event_name == 'push'
    name: Push Compute Benchmarks
    uses: ./.github/workflows/benchmarks-reusable.yml
    with:
      str_name: 'level_zero'
      unit: 'gpu'
      pr_no: 0
      bench_script_params: '--save baseline'
      sycl_config_params: ''
      sycl_repo: 'intel/llvm'
      sycl_commit: ''
