name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  ubuntu-build:
    name: Build - Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install apt packages
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen

    - name: Install pip packages
      run: pip install -r third_party/requirements.txt

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DUR_DEVELOPER_MODE=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUR_BUILD_TESTS=ON

    - name: Generate source from spec, check for uncommitted diff
      run: cmake --build ${{github.workspace}}/build --target check-generated

    - name: Check files format with clang-format
      run: pre-commit run --all-files --show-diff-on-failure

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure -L "python|uma|loader"

  windows-build:
    name: Build - Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install prerequisites
      run: python3 -m pip install -r third_party/requirements.txt

    - name: Configure CMake
      run: cmake -DCMAKE_POLICY_DEFAULT_CMP0094=NEW -DUR_DEVELOPER_MODE=ON -DUR_BUILD_TESTS=ON -B ${{github.workspace}}/build

    - name: Generate source from spec, check for uncommitted diff
      run: cmake --build ${{github.workspace}}/build --target check-generated --config ${{env.BUILD_TYPE}}

    - name: Build all
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure -L "python|uma|loader"
