name: E2E Level Zero

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  e2e-build-hw:
    #if: github.repository == 'oneapi-src/unified-runtime'  # run only on upstream; forks will not have the HW
    name: Start e2e job
    # use core flow, run it with L0 specific parameters
    uses: ./.github/workflows/e2e_core.yml
    with:
      name: "L0"
      runner_tag: "L0_E2E"
      str_name: "level_zero"
      prefix: "ext_oneapi_"
      config: ""
      unit: "gpu"
      # Failing tests
      xfail: "Matrix/SG32/get_coord_int8_matB.cpp;Matrix/element_wise_all_ops_1d.cpp;Matrix/element_wise_all_ops_1d_cont.cpp;Matrix/element_wise_all_ops_scalar.cpp;Matrix/get_coord_int8_matB.cpp;Matrix/joint_matrix_rowmajorA_rowmajorB.cpp;Plugin/level_zero_barrier_optimization.cpp"
      # Flaky tests
      filter_out: "UserDefinedReductions/user_defined_reductions.cpp"
      # These runners by default spawn upwards of 260 workers.
      # We also add a time out just in case some test hangs
      extra_lit_flags: "--param gpu-intel-pvc=True -sv -j 100 --max-time 600"
