# Simple workflow for deploying static content to GitHub Pages
name: Deploy documentation preview

on:
  pull_request:
    paths:
      - 'scripts/**'
    types:
      - opened
      - reopened
      - synchronize
      - closed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

concurrency: preview-${{ github.ref }}

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install apt package
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Install prerequisites
        run: python3 -m pip install -r third_party/requirements.txt

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Build Documentation
        working-directory: ${{github.workspace}}/scripts
        run: python3 run.py --core
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{github.workspace}}/docs/html

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
